# Generated by Django 4.1.6 on 2023-03-18 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FoodieMe', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurantes',
            name='imagen_restaurante',
            field=models.ImageField(default='default.jpg', null=True, upload_to='restaurantes'),
        ),
        migrations.AlterField(
            model_name='experiencias',
            name='fecha_experiencia',
            field=models.DateField(default='0000-00-00'),
        ),
        migrations.AlterField(
            model_name='restaurantes',
            name='fecha_inicio_act',
            field=models.DateField(default='0000-00-00'),
        ),
    ]
